// Compiles sprint/days/day-NN/{person}.md → sprint/data/tasks.js
// Source of truth = the markdown files. Run: node tools/build-sprint.mjs
// Fails loudly on format violations (see sprint/AUTHORING.md).
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import { marked } from 'marked';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DAYS_DIR = path.join(ROOT, 'sprint', 'days');
const PEOPLE = ['avinaya', 'gaurab', 'riya'];
marked.setOptions({ gfm: true });

const errors = [];
const days = [];

const dayDirs = readdirSync(DAYS_DIR).filter(d => /^day-\d{2}$/.test(d)).sort();
for (const dir of dayDirs) {
  const n = parseInt(dir.slice(4), 10);
  const day = { n, people: {} };
  for (const person of PEOPLE) {
    const file = path.join(DAYS_DIR, dir, `${person}.md`);
    if (!existsSync(file)) { errors.push(`${dir}/${person}.md is missing`); continue; }
    const src = readFileSync(file, 'utf8');
    const rel = `${dir}/${person}.md`;

    const h1 = src.match(/^# Day (\d+) — (\w+)/m);
    if (!h1 || parseInt(h1[1], 10) !== n) errors.push(`${rel}: bad or mismatched H1`);
    const objective = (src.match(/\*\*Objective:\*\*\s*(.+)/) || [])[1];
    const time = (src.match(/\*\*Total time:\*\*\s*(.+)/) || [])[1];
    if (!objective) errors.push(`${rel}: missing **Objective:**`);
    if (!time) errors.push(`${rel}: missing **Total time:**`);

    const chunks = src.split(/^## /m).slice(1);
    const tasks = [];
    for (const chunk of chunks) {
      const head = chunk.split('\n')[0];
      const m = head.match(/^Task (\d+) · (🔥|🟡|🟢) (.+?) \(([^)]+)\)\s*$/u);
      if (!m) { errors.push(`${rel}: bad task heading "## ${head}"`); continue; }
      const body = chunk.slice(head.length + 1).trim();
      const dep = (body.match(/\*\*Depends on:\*\*\s*(.+)/) || [, '—'])[1].trim();
      tasks.push({
        id: `d${String(n).padStart(2, '0')}-${person}-t${m[1]}`,
        n: parseInt(m[1], 10),
        pri: m[2],
        title: m[3],
        time: m[4],
        dep: dep === '—' ? null : dep,
        html: marked.parse(body),
      });
    }
    if (tasks.length < 1) errors.push(`${rel}: no tasks parsed`);
    day.people[person] = { objective, time, tasks };
  }
  days.push(day);
}

if (days.length === 0) errors.push('no day folders found');
if (errors.length) {
  console.error('SPRINT BUILD FAILED:\n  ' + errors.join('\n  '));
  process.exit(1);
}

const out = `// GENERATED by tools/build-sprint.mjs — do not edit by hand.
// Edit sprint/days/day-NN/<person>.md and rebuild.
window.SPRINT_DATA = ${JSON.stringify({ generated: new Date().toISOString(), days }, null, 1)};
`;
writeFileSync(path.join(ROOT, 'sprint', 'data', 'tasks.js'), out);
const total = days.reduce((s, d) => s + PEOPLE.reduce((t, p) => t + (d.people[p]?.tasks.length || 0), 0), 0);
console.log(`Built sprint/data/tasks.js — ${days.length} days, ${total} tasks`);
